CONFIG_CPP=y
CONFIG_STD_CPP14=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# needed for stack size measurement
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y

# task switch tracing
CONFIG_TRACING=y
CONFIG_TRACING_USER=y

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
#CONFIG_NET_IPV6=y
CONFIG_NET_ARP=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV4_IGMP=y
#CONFIG_NET_IPV6_MLD=y

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"

CONFIG_NET_LOG=y
#CONFIG_LOG_OVERRIDE_LEVEL=4

#CONFIG_NET_IF_LOG_LEVEL_DBG=y
#CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=y
#CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
#CONFIG_NET_TCP_LOG_LEVEL_DBG=y
#CONFIG_NET_UDP_LOG_LEVEL_DBG=y
#CONFIG_NET_TC_LOG_LEVEL_DBG=y
##CONFIG_NET_PKT_LOG_LEVEL_DBG=y
#CONFIG_NET_UTILS_LOG_LEVEL_DBG=y
#CONFIG_NET_CONTEXT_LOG_LEVEL_DBG=y
#CONFIG_NET_ARP_LOG_LEVEL_DBG=y
#CONFIG_NET_CONN_LOG_LEVEL_DBG=y
#CONFIG_NET_ROUTE_LOG_LEVEL_DBG=y
#CONFIG_NET_CORE_LOG_LEVEL_DBG=y
#CONFIG_NET_MGMT_EVENT_LOG_LEVEL_DBG=y
#CONFIG_NET_IPV4_ACD_LOG_LEVEL_DBG=y
#CONFIG_NET_IPV4_LOG_LEVEL_DBG=y
##CONFIG_NET_IPV6_LOG_LEVEL_DBG=y
#CONFIG_NET_ICMPV4_LOG_LEVEL_DBG=y
##CONFIG_NET_ICMPV6_LOG_LEVEL_DBG=y
#CONFIG_NET_DHCPV4_LOG_LEVEL_DBG=y
##CONFIG_NET_DNS_LOG_LEVEL_DBG=y
##CONFIG_NET_MLD_LOG_LEVEL_DBG=y
##CONFIG_NET_IGMP_LOG_LEVEL_DBG=y
##CONFIG_NET_IPV6_NBR_CACHE_LOG_LEVEL_DBG=y
##CONFIG_NET_IPV6_PE_LOG_LEVEL_DBG=y
##CONFIG_NET_IPV6_ND_LOG_LEVEL_DBG=y
#CONFIG_NET_BUF_LOG_LEVEL_DBG=y
#CONFIG_NET_CONFIG_LOG_LEVEL_DBG=y
